### PR TITLE
new contribution

### PR DESCRIPTION
**Pull request by oooo-ankit**
https://leetcode.com/problems/count-hills-and-valleys-in-an-array/
https://leetcode.com/problems/find-pivot-index/
https://leetcode.com/problems/count-primes/
https://leetcode.com/problems/rotate-array/
https://leetcode.com/problems/search-a-2d-matrix-ii/

### CODE REVIEW

**Review by code-chaser — CHANGES_REQUESTED** [review]
Submission links please, it's hard to check every solution manually 😓.
Thanks!

**Comment by oooo-ankit** [comment]
> Submission links please, it's hard to check every solution manually 😓. 
My apologies. Where should I add the submission links? I have already given the question links but I will also add the submission links asap.

**Comment by code-chaser** [comment]
You can put them here, in this comments section.

**Comment by oooo-ankit** [comment]
https://leetcode.com/problems/count-hills-and-valleys-in-an-array/
https://leetcode.com/problems/find-pivot-index/
https://leetcode.com/problems/count-primes/
https://leetcode.com/problems/rotate-array/
https://leetcode.com/problems/search-a-2d-matrix-ii/

**Comment by code-chaser** [comment]
@oooo-ankit, I was asking for submission links, like this one: https://leetcode.com/submissions/detail/818465057/.

Not problem links.

Anyways, I've verified them manually, they are correct solutions so I can merge your PR.

**Review by code-chaser — APPROVED** [review]
- Solutions verified manually ✅ 
- PR can be merged 🎉

**Pull request merged**
